name: ActionTracker
version: 1.0
api-version: 1.13
main: me.tazadejava.actiontracker.ActionTrackerPlugin
commands:
  mission:
    description: Main command to handle mission data tracking requests.
    permission: oponly
permissions:
  oponly:
    description: Allows usage of mission command.
    default: op